format = "[░▒▓](darkOnPrimary)[ 󱄅 ](bg:darkOnPrimary fg:#FFFFFF)[](bg:darkOnPrimary fg:darkOnPrimaryFixedVariant)[](bg:darkOnPrimaryFixedVariant fg:darkInversePrimary)$directory[](fg:darkInversePrimary)$fill[](fg:darkInversePrimary)$git_branch$git_status[](bg:darkOnPrimaryFixedVariant fg:darkInversePrimary)$nodejs$bun$rust$golang$php[](bg:darkOnPrimary fg:darkOnPrimaryFixedVariant)$time[▓▒░](fg:darkOnPrimary)\n$character"
palette = "dms"

[bun]
format = "[[ $symbol ($version) ](fg:#FFFFFF bg:darkOnPrimaryFixedVariant)]($style)"
style = "bg:darkOnPrimaryFixedVariant"
symbol = ""

[character]
error_symbol = "[❯](#FF5C57)"
success_symbol = "[❯](#E6E6FF)"
vimcmd_symbol = "[❮](#6905F7)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[directory]
format = "[ $path ]($style)"
style = "fg:#FFFFFF bg:darkInversePrimary"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙 "
Downloads = " "
Music = " "
Pictures = " "

[fill]
symbol = " "

[git_branch]
format = "[[ $symbol $branch ](fg:#FFFFFF bg:darkOnPrimaryFixedVariant)]($style)"
style = "bg:darkOnPrimaryFixedVariant"
symbol = ""

[git_status]
format = "[[($all_status$ahead_behind )](fg:#FFFFFF bg:darkOnPrimaryFixedVariant)]($style)"
style = "bg:darkOnPrimaryFixedVariant"

[golang]
format = "[[ $symbol ($version) ](fg:#FFFFFF bg:darkOnPrimaryFixedVariant)]($style)"
style = "bg:darkOnPrimaryFixedVariant"
symbol = ""

[nix_shell]
format = "[$symbol]($style)"
symbol = "❄️ "

[nodejs]
format = "[[ $symbol ($version) ](fg:#FFFFFF bg:darkOnPrimaryFixedVariant)]($style)"
style = "bg:darkOnPrimaryFixedVariant"
symbol = ""

[php]
format = "[[ $symbol ($version) ](fg:#FFFFFF bg:darkOnPrimaryFixedVariant)]($style)"
style = "bg:darkOnPrimaryFixedVariant"
symbol = ""

[rust]
format = "[[ $symbol ($version) ](fg:#FFFFFF bg:darkOnPrimaryFixedVariant)]($style)"
style = "bg:darkOnPrimaryFixedVariant"
symbol = ""

[shell]
bash_indicator = ""
disabled = false
powershell_indicator = ""
style = "cyan"

[time]
disabled = false
format = "[[  $time ](fg:#FFFFFF bg:darkOnPrimary)]($style)"
style = "bg:darkOnPrimary"
time_format = "%R"

[palettes.dms]
darkOnPrimary = "#0A0373"
darkOnPrimaryFixedVariant = "#1C1690"
darkInversePrimary = "#3A36B5"
