palette = "dms"

format = """
[░▒▓](fg:color1)\
[ 󱄅 ](fg:color4 bg:color1)\
[](fg:color4 bg:color1)\
[](fg:color2 bg:color4)\
${custom.javascript}\
${custom.typescript}\
$bun\
$lua\
${custom.nix}\
$rust\
$golang\
$php\
$python\
$java\
$kotlin\
$c\
$cpp\
$zig\
$haskell\
$elixir\
$terraform\
$nix_shell\
$docker_context\
${custom.docker}\
${custom.toml}\
${custom.yaml}\
${custom.json}\
[](fg:color3 bg:color2)\
$directory\
[](fg:color3)\
$fill\
[](fg:color3)\
$git_branch$git_status\
[](fg:color3 bg:color2)\
$git_metrics\
[](fg:color2 bg:color4)\
[](fg:color4 bg:color1)\
$time\
[▓▒░](fg:color1)\
\n$character
"""

[palettes.dms]
color1 = "#0A0373"  # Darkest Bar Color
color2 = "#1C1690"  # Middle Bar Color
color3 = "#3A36B5"  # Lightest Bar Color
color4 = "#FFFFFF"  # Text & Static Sperator Color
color5 = "#60FF60" # Git Lines Added Color
color6 = "#FF6060" # Git Lines Removed Color
color7 = "#000000"# Spare
cursor1 = "#FF5C57"
cursor2 = "#FFFFFF"
cursor3 = "#6905F7"
# ─────────────────────────────
# DIRECTORY
# ─────────────────────────────
[directory]
format = "[ $path ](fg:color4 bg:color3)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~/Desktop" = " Desktop"
"~/Documents" = "󰈙 Documents"
"~/Downloads" = " Downloads"
"~/Pictures" = " Pictures"
"~/Videos" = " Videos"
"~/Music" = " Music"
"~/Projects" = "󰲋 Projects"
"~/Dev" = "󰅨 Dev"
"~/Code" = "󰨞 Code"
"~/Git" = "󰊢 Git"
"~/NixOS" = " NixOS"
"~/Workspace" = "󰙅 Workspace"

# ─────────────────────────────
# GIT
# ─────────────────────────────
[git_branch]
format = "[ $symbol $branch ](fg:color4 bg:color3)"
symbol = ""

[git_status]
format = "([$all_status $ahead_behind ](fg:color4 bg:color3))"

conflicted = "🏳"
untracked = "?"
stashed = "📦"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
typechanged = ""

ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count} ⇣${behind_count}"
up_to_date = "✓"

style = "fg:color4 bg:color3"

[git_metrics]
disabled = false
format = "([ +$added ]($added_style)[-$deleted ]($deleted_style))"

added_style = "fg:color5 bg:color2 bold"
deleted_style = "fg:color6 bg:color2 bold"

only_nonzero_diffs = true
ignore_submodules = false

# ─────────────────────────────
# LANGUAGES
# ─────────────────────────────

[custom.javascript]
command = "echo  "
detect_extensions = ["js", "mjs", "cjs", "!node_modules"]
format = "[ $output ](fg:color4 bg:color2)"

[custom.typescript]
command = "echo   "
detect_extensions = ["ts", "tsx", "!node_modules"]
format = "[ $output ](fg:color4 bg:color2)"

[bun]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[lua]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[custom.nix]
command = "echo nix "
detect_extensions = ["nix", "!NixOS"]
format = "[ $output ](fg:color4 bg:color2)"

[rust]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[golang]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[php]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[python]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[java]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[kotlin]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[c]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[cpp]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[zig]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[haskell]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[elixir]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = ""

[terraform]
format = "[ $symbol ($version) ](fg:color4 bg:color2)"
symbol = "󱁢"

[nix_shell]
format = "[ $symbol ](fg:color4 bg:color2)"
symbol = ""

[docker_context]
format = "[ $symbol $context ](fg:color4 bg:color2)"
symbol = ""

[custom.docker]
command = "echo  "
detect_files = ["Dockerfile", "docker-compose.yml", "compose.yml", "compose.yaml"]
format = "[ $output ](fg:color4 bg:color2)"

[custom.toml]
command = "echo "
detect_extensions = ["toml"]
format = "[ $output ](fg:color4 bg:color2)"

[custom.yaml]
command = "echo \ue8eb"
detect_extensions = ["yml", "yaml"]
format = "[ $output ](fg:color4 bg:color2)"

[custom.json]
command = "echo  "
detect_extensions = ["json"]
format = "[ $output ](fg:color4 bg:color2)"



# ─────────────────────────────
# TIME
# ─────────────────────────────
[time]
disabled = false
format = "[  $time ](fg:color4 bg:color1)"
time_format = "%R"

# ─────────────────────────────
# FILL
# ─────────────────────────────
[fill]
symbol = " "

# ─────────────────────────────
# CHARACTER
# ─────────────────────────────
[character]
error_symbol = "[❯](cursor1)"
success_symbol = "[❯](cursor2)"
vimcmd_symbol = "[❮](cursor3)"
