# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-root";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-root".device = "/dev/disk/by-uuid/d866a608-b476-40cd-a7c9-c9dbd1e0cf93";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3C4E-08F8";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/var/lib/docker/rootfs/overlayfs/544f44de4903c4590a96ced52fe9403f448afba85ba29da149a6a96b3bc01981" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/var/lib/docker/rootfs/overlayfs/0e0918e8c7c736cd435581740ad41bd10986c56c6b900d3b83f159f547638fb4" =
    { device = "overlay";
      fsType = "overlay";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/979234ae-8a46-4a49-9e83-99ad21bcfd61"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
